"""Self-optimization engine — the platform improves itself.

Per the build brief, the platform shall be self-improving and self-optimising
within governance constraints. This engine:
- Analyzes platform performance metrics
- Identifies bottlenecks and inefficiencies
- Generates optimization recommendations
- Auto-tunes parameters within safe bounds
- All material changes require owner veto review
"""

import uuid
from datetime import datetime, timedelta, timezone

from sqlalchemy import Column, DateTime, Float, String, Integer, Boolean, Text, select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.database.db import Base
from app.exchange.orderbook import Order, Trade, OrderStatus
from app.agents.models import Agent, Wallet
from app.blockchain.chain import Blockchain


class OptimizationRecommendation(Base):
    """A recommendation generated by the self-optimization engine."""
    __tablename__ = "optimization_recommendations"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    category = Column(String(50), nullable=False)       # performance, liquidity, security, growth
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    impact_score = Column(Float, default=0.0)           # 0-10 estimated impact
    auto_applicable = Column(Boolean, default=False)    # Can be auto-applied without veto
    applied = Column(Boolean, default=False)
    dismissed = Column(Boolean, default=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class PerformanceSnapshot(Base):
    """Periodic snapshot of platform performance metrics."""
    __tablename__ = "performance_snapshots"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    total_agents = Column(Integer, default=0)
    active_agents_24h = Column(Integer, default=0)
    total_transactions = Column(Integer, default=0)
    trades_24h = Column(Integer, default=0)
    trade_volume_24h = Column(Float, default=0.0)
    open_orders = Column(Integer, default=0)
    active_loans = Column(Integer, default=0)
    chain_length = Column(Integer, default=0)
    pending_tx = Column(Integer, default=0)
    avg_block_size = Column(Float, default=0.0)


class SelfOptimizationEngine:
    """Analyzes and optimizes platform performance automatically."""

    # Tunable parameters with safe bounds
    TUNABLE_PARAMS = {
        "mining_threshold": {"current": 10, "min": 5, "max": 50, "unit": "transactions"},
        "rate_refresh_interval": {"current": 300, "min": 60, "max": 3600, "unit": "seconds"},
        "order_book_depth": {"current": 20, "min": 10, "max": 100, "unit": "levels"},
        "max_pending_tx": {"current": 100, "min": 10, "max": 1000, "unit": "transactions"},
    }

    def __init__(self, blockchain: Blockchain):
        self.blockchain = blockchain

    async def take_snapshot(self, db: AsyncSession) -> PerformanceSnapshot:
        """Capture current platform performance metrics."""
        now = datetime.now(timezone.utc)
        day_ago = now - timedelta(hours=24)

        total_agents = (await db.execute(select(func.count(Agent.id)))).scalar() or 0
        active_24h = (await db.execute(
            select(func.count(Agent.id)).where(Agent.last_active >= day_ago)
        )).scalar() or 0

        chain_info = self.blockchain.get_chain_info()

        trades_24h = (await db.execute(
            select(func.count(Trade.id)).where(Trade.executed_at >= day_ago)
        )).scalar() or 0
        volume_24h = (await db.execute(
            select(func.sum(Trade.total_value)).where(Trade.executed_at >= day_ago)
        )).scalar() or 0.0

        open_orders = (await db.execute(
            select(func.count(Order.id)).where(
                Order.status.in_([OrderStatus.OPEN, OrderStatus.PARTIALLY_FILLED])
            )
        )).scalar() or 0

        # Average block size
        total_tx = chain_info["total_transactions"]
        blocks = max(chain_info["chain_length"] - 1, 1)  # Exclude genesis
        avg_block = total_tx / blocks if blocks > 0 else 0

        snapshot = PerformanceSnapshot(
            total_agents=total_agents,
            active_agents_24h=active_24h,
            total_transactions=total_tx,
            trades_24h=trades_24h,
            trade_volume_24h=round(volume_24h or 0, 4),
            open_orders=open_orders,
            chain_length=chain_info["chain_length"],
            pending_tx=chain_info["pending_transactions"],
            avg_block_size=round(avg_block, 1),
        )
        db.add(snapshot)
        await db.flush()
        return snapshot

    async def analyze_and_recommend(self, db: AsyncSession) -> list[dict]:
        """Analyze platform state and generate optimization recommendations."""
        recommendations = []
        chain_info = self.blockchain.get_chain_info()
        now = datetime.now(timezone.utc)
        day_ago = now - timedelta(hours=24)

        # 1. Check pending transaction backlog
        if chain_info["pending_transactions"] > 50:
            rec = OptimizationRecommendation(
                category="performance",
                title="High pending transaction backlog",
                description=(
                    f"{chain_info['pending_transactions']} transactions pending. "
                    f"Consider reducing mining threshold from {self.TUNABLE_PARAMS['mining_threshold']['current']} "
                    f"to trigger more frequent block mining."
                ),
                impact_score=7.0,
                auto_applicable=True,
            )
            db.add(rec)
            recommendations.append({"id": rec.id, "title": rec.title, "impact": rec.impact_score, "auto": True})

        # 2. Check order book health
        open_orders = (await db.execute(
            select(func.count(Order.id)).where(
                Order.status.in_([OrderStatus.OPEN, OrderStatus.PARTIALLY_FILLED])
            )
        )).scalar() or 0

        trades_24h = (await db.execute(
            select(func.count(Trade.id)).where(Trade.executed_at >= day_ago)
        )).scalar() or 0

        if open_orders > 0 and trades_24h == 0:
            rec = OptimizationRecommendation(
                category="liquidity",
                title="Open orders with no trades in 24h",
                description=(
                    f"{open_orders} open orders but 0 trades in the last 24h. "
                    f"The market may need more participants or tighter spreads."
                ),
                impact_score=5.0,
                auto_applicable=False,
            )
            db.add(rec)
            recommendations.append({"id": rec.id, "title": rec.title, "impact": rec.impact_score, "auto": False})

        # 3. Check agent growth
        total_agents = (await db.execute(select(func.count(Agent.id)))).scalar() or 0
        active_24h = (await db.execute(
            select(func.count(Agent.id)).where(Agent.last_active >= day_ago)
        )).scalar() or 0

        if total_agents > 0 and active_24h / total_agents < 0.1:
            rec = OptimizationRecommendation(
                category="growth",
                title="Low agent retention rate",
                description=(
                    f"Only {active_24h}/{total_agents} agents active in 24h "
                    f"({active_24h/total_agents*100:.0f}% retention). "
                    f"Consider increasing outreach via the discovery API."
                ),
                impact_score=6.0,
                auto_applicable=False,
            )
            db.add(rec)
            recommendations.append({"id": rec.id, "title": rec.title, "impact": rec.impact_score, "auto": False})

        # 4. Auto-mine if backlog is critical
        if chain_info["pending_transactions"] > 80:
            self.blockchain.force_mine()
            rec = OptimizationRecommendation(
                category="performance",
                title="Auto-mined: critical transaction backlog",
                description=f"Automatically mined block due to {chain_info['pending_transactions']} pending transactions.",
                impact_score=8.0,
                auto_applicable=True,
                applied=True,
            )
            db.add(rec)
            recommendations.append({"id": rec.id, "title": rec.title, "impact": rec.impact_score, "auto": True, "applied": True})

        await db.flush()
        return recommendations

    async def get_recommendations(
        self, db: AsyncSession, applied: bool | None = None, limit: int = 50
    ) -> list[dict]:
        """Get optimization recommendations."""
        query = select(OptimizationRecommendation).where(
            OptimizationRecommendation.dismissed == False
        )
        if applied is not None:
            query = query.where(OptimizationRecommendation.applied == applied)
        query = query.order_by(OptimizationRecommendation.impact_score.desc()).limit(limit)
        result = await db.execute(query)
        return [
            {
                "id": r.id, "category": r.category, "title": r.title,
                "description": r.description, "impact_score": r.impact_score,
                "auto_applicable": r.auto_applicable, "applied": r.applied,
                "created_at": str(r.created_at),
            }
            for r in result.scalars().all()
        ]

    async def get_performance_history(
        self, db: AsyncSession, limit: int = 30
    ) -> list[dict]:
        """Get historical performance snapshots."""
        result = await db.execute(
            select(PerformanceSnapshot)
            .order_by(PerformanceSnapshot.timestamp.desc())
            .limit(limit)
        )
        return [
            {
                "timestamp": str(s.timestamp),
                "agents": s.total_agents, "active_24h": s.active_agents_24h,
                "trades_24h": s.trades_24h, "volume_24h": s.trade_volume_24h,
                "open_orders": s.open_orders, "chain_length": s.chain_length,
                "pending_tx": s.pending_tx, "avg_block": s.avg_block_size,
            }
            for s in result.scalars().all()
        ]

    def get_tunable_parameters(self) -> dict:
        """Get current tunable parameters and their bounds."""
        return self.TUNABLE_PARAMS
