"""Self-optimization engine — the platform improves itself within strict bounds.

Per the build brief, the platform shall be self-improving and self-optimising
within governance constraints. This engine:
- Analyzes platform performance metrics
- Identifies bottlenecks and inefficiencies
- Generates optimization recommendations
- Auto-tunes ONLY non-financial operational parameters within safe bounds
- All material changes require owner veto review

REGULATORY COMPLIANCE GUARDRAILS (Section 5 — Self-Improvement Bounds):
The engine is PROHIBITED from autonomously modifying:
- Fee rates, commission structures, or any financial parameters
- Wallet balances, transaction records, or blockchain data
- Authentication, authorization, or security configurations
- KYC/AML thresholds or compliance rules
- Smart contract logic or agent trust scores
- Charity allocation rates or payout configurations
- Any code, database schemas, or deployment configurations

The engine MAY autonomously:
- Mine pending transaction blocks (operational, not financial)
- Generate non-binding recommendations for owner review
- Adjust operational thresholds within pre-defined safe bounds

All autonomous actions are logged to an immutable audit trail.
"""

import uuid
import logging
from datetime import datetime, timedelta, timezone

from sqlalchemy import Column, DateTime, Float, String, Integer, Boolean, Text, select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.database.db import Base
from app.exchange.orderbook import Order, Trade, OrderStatus
from app.agents.models import Agent, Wallet
from app.blockchain.chain import Blockchain

logger = logging.getLogger(__name__)


# ── Guardrail Definitions ────────────────────────────────────────────────
# These lists define what the engine is explicitly allowed and prohibited
# from touching. Any action not in ALLOWED_ACTIONS is denied by default.

ALLOWED_AUTO_ACTIONS = frozenset({
    "force_mine",                # Mine pending blocks when backlog is critical
})

PROHIBITED_DOMAINS = frozenset({
    "fee_rates",                 # Commission rates, charity rates
    "wallet_balances",           # Any wallet balance modification
    "transaction_records",       # Blockchain transaction history
    "authentication",            # Auth config, tokens, secrets
    "kyc_aml",                   # KYC levels, AML thresholds
    "compliance_rules",          # SARB limits, regulatory settings
    "smart_contracts",           # Contract logic
    "trust_scores",              # Agent reputation/trust scores
    "payout_config",             # Payout destinations, splits, schedules
    "code_deployment",           # Source code, migrations, deployments
    "database_schema",           # Table structures
    "security_config",           # TLS, CORS, rate limits
})

# Maximum autonomous actions per hour to prevent runaway behaviour
MAX_AUTO_ACTIONS_PER_HOUR = 5


class OptimizationAuditLog(Base):
    """Immutable audit trail for every autonomous action taken by the engine."""
    __tablename__ = "optimization_audit_log"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    timestamp = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    action = Column(String(100), nullable=False)        # e.g. "force_mine"
    reason = Column(Text, nullable=False)                # Why the action was taken
    details = Column(Text, nullable=True)                # Additional context
    was_allowed = Column(Boolean, nullable=False)        # Whether guardrail permitted it
    guardrail_check = Column(String(255), nullable=True) # Which guardrail was evaluated


class OptimizationRecommendation(Base):
    """A recommendation generated by the self-optimization engine."""
    __tablename__ = "optimization_recommendations"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    category = Column(String(50), nullable=False)       # performance, liquidity, security, growth
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    impact_score = Column(Float, default=0.0)           # 0-10 estimated impact
    auto_applicable = Column(Boolean, default=False)    # Can be auto-applied without veto
    applied = Column(Boolean, default=False)
    dismissed = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class PerformanceSnapshot(Base):
    """Periodic snapshot of platform performance metrics."""
    __tablename__ = "performance_snapshots"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    timestamp = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    total_agents = Column(Integer, default=0)
    active_agents_24h = Column(Integer, default=0)
    total_transactions = Column(Integer, default=0)
    trades_24h = Column(Integer, default=0)
    trade_volume_24h = Column(Float, default=0.0)
    open_orders = Column(Integer, default=0)
    active_loans = Column(Integer, default=0)
    chain_length = Column(Integer, default=0)
    pending_tx = Column(Integer, default=0)
    avg_block_size = Column(Float, default=0.0)


class SelfOptimizationEngine:
    """Analyzes and optimizes platform performance within strict regulatory bounds.

    GUARDRAILS:
    - Only actions in ALLOWED_AUTO_ACTIONS can execute autonomously
    - All autonomous actions are audit-logged (immutable)
    - Rate-limited to MAX_AUTO_ACTIONS_PER_HOUR per hour
    - PROHIBITED_DOMAINS cannot be touched under any circumstances
    - Recommendations are always non-binding (require owner approval)
    """

    # Tunable parameters with safe bounds (operational only, never financial)
    TUNABLE_PARAMS = {
        "mining_threshold": {"current": 10, "min": 5, "max": 50, "unit": "transactions",
                             "domain": "operational", "auto_tunable": False},
        "rate_refresh_interval": {"current": 300, "min": 60, "max": 3600, "unit": "seconds",
                                  "domain": "operational", "auto_tunable": False},
        "order_book_depth": {"current": 20, "min": 10, "max": 100, "unit": "levels",
                             "domain": "operational", "auto_tunable": False},
        "max_pending_tx": {"current": 100, "min": 10, "max": 1000, "unit": "transactions",
                           "domain": "operational", "auto_tunable": False},
    }

    def __init__(self, blockchain: Blockchain):
        self.blockchain = blockchain
        self._auto_action_timestamps: list[datetime] = []

    def _check_guardrail(self, action: str) -> tuple[bool, str]:
        """Check if an autonomous action is permitted by guardrails.

        Returns (allowed, reason).
        """
        if action not in ALLOWED_AUTO_ACTIONS:
            return False, f"Action '{action}' not in ALLOWED_AUTO_ACTIONS whitelist"

        # Rate limiting
        now = datetime.now(timezone.utc)
        hour_ago = now - timedelta(hours=1)
        self._auto_action_timestamps = [
            t for t in self._auto_action_timestamps if t > hour_ago
        ]
        if len(self._auto_action_timestamps) >= MAX_AUTO_ACTIONS_PER_HOUR:
            return False, f"Rate limit exceeded: {MAX_AUTO_ACTIONS_PER_HOUR} actions/hour"

        return True, "Guardrail check passed"

    async def _log_audit(
        self, db: AsyncSession, action: str, reason: str,
        was_allowed: bool, guardrail_check: str, details: str = ""
    ) -> None:
        """Log an autonomous action to the immutable audit trail."""
        log_entry = OptimizationAuditLog(
            action=action,
            reason=reason,
            details=details,
            was_allowed=was_allowed,
            guardrail_check=guardrail_check,
        )
        db.add(log_entry)
        await db.flush()
        logger.info(
            f"OptEngine audit: action={action} allowed={was_allowed} "
            f"reason={reason} guardrail={guardrail_check}"
        )

    async def take_snapshot(self, db: AsyncSession) -> PerformanceSnapshot:
        """Capture current platform performance metrics (read-only, always safe)."""
        now = datetime.now(timezone.utc)
        day_ago = now - timedelta(hours=24)

        total_agents = (await db.execute(select(func.count(Agent.id)))).scalar() or 0
        active_24h = (await db.execute(
            select(func.count(Agent.id)).where(Agent.last_active >= day_ago)
        )).scalar() or 0

        chain_info = self.blockchain.get_chain_info()

        trades_24h = (await db.execute(
            select(func.count(Trade.id)).where(Trade.executed_at >= day_ago)
        )).scalar() or 0
        volume_24h = (await db.execute(
            select(func.sum(Trade.total_value)).where(Trade.executed_at >= day_ago)
        )).scalar() or 0.0

        open_orders = (await db.execute(
            select(func.count(Order.id)).where(
                Order.status.in_([OrderStatus.OPEN, OrderStatus.PARTIALLY_FILLED])
            )
        )).scalar() or 0

        total_tx = chain_info["total_transactions"]
        blocks = max(chain_info["chain_length"] - 1, 1)
        avg_block = total_tx / blocks if blocks > 0 else 0

        snapshot = PerformanceSnapshot(
            total_agents=total_agents,
            active_agents_24h=active_24h,
            total_transactions=total_tx,
            trades_24h=trades_24h,
            trade_volume_24h=round(volume_24h or 0, 4),
            open_orders=open_orders,
            chain_length=chain_info["chain_length"],
            pending_tx=chain_info["pending_transactions"],
            avg_block_size=round(avg_block, 1),
        )
        db.add(snapshot)
        await db.flush()
        return snapshot

    async def analyze_and_recommend(self, db: AsyncSession) -> list[dict]:
        """Analyze platform state and generate optimization recommendations.

        All recommendations are NON-BINDING and require owner approval.
        The only autonomous action is emergency block mining (guardrail-checked).
        """
        recommendations = []
        chain_info = self.blockchain.get_chain_info()
        now = datetime.now(timezone.utc)
        day_ago = now - timedelta(hours=24)

        # 1. Check pending transaction backlog (recommendation only)
        if chain_info["pending_transactions"] > 50:
            rec = OptimizationRecommendation(
                category="performance",
                title="High pending transaction backlog",
                description=(
                    f"{chain_info['pending_transactions']} transactions pending. "
                    f"Consider reducing mining threshold from {self.TUNABLE_PARAMS['mining_threshold']['current']} "
                    f"to trigger more frequent block mining."
                ),
                impact_score=7.0,
                auto_applicable=False,  # Recommendations are never auto-applied
            )
            db.add(rec)
            recommendations.append({
                "id": rec.id, "title": rec.title,
                "impact": rec.impact_score, "auto": False,
            })

        # 2. Check order book health (recommendation only)
        open_orders = (await db.execute(
            select(func.count(Order.id)).where(
                Order.status.in_([OrderStatus.OPEN, OrderStatus.PARTIALLY_FILLED])
            )
        )).scalar() or 0

        trades_24h = (await db.execute(
            select(func.count(Trade.id)).where(Trade.executed_at >= day_ago)
        )).scalar() or 0

        if open_orders > 0 and trades_24h == 0:
            rec = OptimizationRecommendation(
                category="liquidity",
                title="Open orders with no trades in 24h",
                description=(
                    f"{open_orders} open orders but 0 trades in the last 24h. "
                    f"The market may need more participants or tighter spreads."
                ),
                impact_score=5.0,
                auto_applicable=False,
            )
            db.add(rec)
            recommendations.append({
                "id": rec.id, "title": rec.title,
                "impact": rec.impact_score, "auto": False,
            })

        # 3. Check agent retention (recommendation only)
        total_agents = (await db.execute(select(func.count(Agent.id)))).scalar() or 0
        active_24h = (await db.execute(
            select(func.count(Agent.id)).where(Agent.last_active >= day_ago)
        )).scalar() or 0

        if total_agents > 0 and active_24h / total_agents < 0.1:
            rec = OptimizationRecommendation(
                category="growth",
                title="Low agent retention rate",
                description=(
                    f"Only {active_24h}/{total_agents} agents active in 24h "
                    f"({active_24h/total_agents*100:.0f}% retention). "
                    f"Consider increasing outreach via the discovery API."
                ),
                impact_score=6.0,
                auto_applicable=False,
            )
            db.add(rec)
            recommendations.append({
                "id": rec.id, "title": rec.title,
                "impact": rec.impact_score, "auto": False,
            })

        # 4. Emergency auto-mine ONLY if backlog is critical (guardrail-checked)
        if chain_info["pending_transactions"] > 80:
            allowed, guardrail_msg = self._check_guardrail("force_mine")

            if allowed:
                self.blockchain.force_mine()
                self._auto_action_timestamps.append(now)

                await self._log_audit(
                    db, action="force_mine",
                    reason=f"Critical backlog: {chain_info['pending_transactions']} pending transactions",
                    was_allowed=True,
                    guardrail_check="ALLOWED_AUTO_ACTIONS + rate_limit",
                    details=f"Threshold: 80, Actual: {chain_info['pending_transactions']}",
                )

                rec = OptimizationRecommendation(
                    category="performance",
                    title="Auto-mined: critical transaction backlog",
                    description=(
                        f"Automatically mined block due to {chain_info['pending_transactions']} "
                        f"pending transactions. Guardrail check passed. "
                        f"Action logged to audit trail."
                    ),
                    impact_score=8.0,
                    auto_applicable=True,
                    applied=True,
                )
                db.add(rec)
                recommendations.append({
                    "id": rec.id, "title": rec.title,
                    "impact": rec.impact_score, "auto": True, "applied": True,
                })
            else:
                await self._log_audit(
                    db, action="force_mine",
                    reason=f"Critical backlog: {chain_info['pending_transactions']} pending",
                    was_allowed=False,
                    guardrail_check=guardrail_msg,
                )
                logger.warning(f"OptEngine: force_mine BLOCKED by guardrail: {guardrail_msg}")

        await db.flush()
        return recommendations

    async def get_recommendations(
        self, db: AsyncSession, applied: bool | None = None, limit: int = 50
    ) -> list[dict]:
        """Get optimization recommendations."""
        query = select(OptimizationRecommendation).where(
            OptimizationRecommendation.dismissed == False
        )
        if applied is not None:
            query = query.where(OptimizationRecommendation.applied == applied)
        query = query.order_by(OptimizationRecommendation.impact_score.desc()).limit(limit)
        result = await db.execute(query)
        return [
            {
                "id": r.id, "category": r.category, "title": r.title,
                "description": r.description, "impact_score": r.impact_score,
                "auto_applicable": r.auto_applicable, "applied": r.applied,
                "created_at": str(r.created_at),
            }
            for r in result.scalars().all()
        ]

    async def get_audit_log(self, db: AsyncSession, limit: int = 100) -> list[dict]:
        """Get the immutable audit trail of all autonomous actions."""
        result = await db.execute(
            select(OptimizationAuditLog)
            .order_by(OptimizationAuditLog.timestamp.desc())
            .limit(limit)
        )
        return [
            {
                "id": e.id, "timestamp": str(e.timestamp), "action": e.action,
                "reason": e.reason, "details": e.details,
                "was_allowed": e.was_allowed, "guardrail_check": e.guardrail_check,
            }
            for e in result.scalars().all()
        ]

    async def get_performance_history(
        self, db: AsyncSession, limit: int = 30
    ) -> list[dict]:
        """Get historical performance snapshots."""
        result = await db.execute(
            select(PerformanceSnapshot)
            .order_by(PerformanceSnapshot.timestamp.desc())
            .limit(limit)
        )
        return [
            {
                "timestamp": str(s.timestamp),
                "agents": s.total_agents, "active_24h": s.active_agents_24h,
                "trades_24h": s.trades_24h, "volume_24h": s.trade_volume_24h,
                "open_orders": s.open_orders, "chain_length": s.chain_length,
                "pending_tx": s.pending_tx, "avg_block": s.avg_block_size,
            }
            for s in result.scalars().all()
        ]

    def get_tunable_parameters(self) -> dict:
        """Get current tunable parameters and their bounds."""
        return {
            "parameters": self.TUNABLE_PARAMS,
            "guardrails": {
                "allowed_auto_actions": list(ALLOWED_AUTO_ACTIONS),
                "prohibited_domains": list(PROHIBITED_DOMAINS),
                "max_auto_actions_per_hour": MAX_AUTO_ACTIONS_PER_HOUR,
                "note": "All recommendations require owner approval. "
                        "Only emergency block mining can execute autonomously.",
            },
        }
